kinder: add leftover test workflows for 1.21
kubernetes/kubeadm pull request #2431
Opened 2021-04-03 05:27 UTC by RA489

xref https://github.com/kubernetes/kubeadm/pull/2412#pullrequestreview-626238534

2021-04-03 05:28 UTC, RA489 commented
https://github.com/kubernetes/kubeadm/issues/2362

2021-04-03 17:50 UTC, neolit123 requested changes
skew-kubelet-1.20-on-latest.yaml is missing.

2021-04-03 17:50 UTC, neolit123 commented on kinder/ci/workflows/skew-kubelet-1.20-on-1.21.yaml
>    kubernetesVersion: "{{ resolve `ci/latest` }}"
```suggestion
  kubernetesVersion: "{{ resolve `ci/latest-1.21` }}"
```

2021-04-03 17:51 UTC, neolit123 commented on kinder/ci/workflows/skew-kubelet-1.19-on-1.21.yaml
>    kubernetesVersion: "{{ resolve `ci/latest` }}"
```suggestion
  kubernetesVersion: "{{ resolve `ci/latest-1.21` }}"
```

2021-04-05 05:06 UTC, RA489 commented
updated the PR in https://github.com/kubernetes/kubeadm/pull/2412

2021-04-05 05:06 UTC, closed without merging